---
title: "about me"
hidden: true
---

Hi! I'm Andrew. I live in Ann Arbor MI, and currently work at the University of Michigan's School of Social Work. I'm attached to the [Child & Adolescent Data Lab](https://ssw-datalab.org) as a data analyst where my work focuses on cleaning and analyzing administrative data from child welfare and juvenile justice systems. Our research focuses largely on integrating and linking allied service systems to study family and youth outcomes to inform practice and policy. Some of the publications and projects I've worked on can be found in [my CV](https://www.github.com/mooreaw/cv/), and other information can be found on the lab's website.

Most of my day-to-day work involves the `R` language and other open-source software, so I like to keep tabs on new packages and updates from the community. For the past 3 years, I've helped out with the local [R User Group](https://annarborrusergroup.github.io/) as a co-organizer (usually as a workshop instructor, but occasionally giving talks). I'm also interested in open science and the reproducibility movement that's being expressed in various forms across scientific communities. Much of the data I work with is sensitive and carries privacy concerns, but I'm interested in learning how research transparency and reproducibility practices can be fostered among social scientists.

Aside from my academic interests, I like looking at analog/handmade data visualizations and maps, finding unique beers with my partner, traveling, playing strategy games (like Go), and feeding an expanding reading list.

I've started this page/blog as a way to curate thoughts, and explore different datasets and methods that I'm trying to learn about. I hope at the very least I'll have some interesting (if not useful) things for you to read. In that vein, any views expressed here are solely mine and not those of my employer or colleagues.
