---
title: a primer for linear regression (part 2)
author: Andrew
date: '2021-03-12'
slug: primer-for-linear-regression-pt2
categories: []
tags:
  - statistics
  - linear regression
  - R
bibliography: [../../static/bib/references-regression-primer-pt2.bib]
link-citations: true
---



<p>In the <a href="/post/primer-for-linear-regression-p1">previous post</a> of this series, we covered an overview of the <em>Ordinary Least Squares</em> method for estimating the <em>parameters</em> of a linear regression model. While I didn’t give you a full tour of the mathematical guts underpinning the technique, I’ve hopefully given you a sense of the problem the model is attempting to solve, as well as some specific vocabulary that describes the contents of a linear regression. In this post, we’re going to continue working with the <code>{palmerpenguins}</code> data, but we’ll actually cover the task of fitting a model in R, and inspecting the results. Some of what we’ll cover is basic R, but we’ll also use a handful of functions from <code>{broom}</code>, which is a really handy package for wrangling information out of the objects that R creates to store linear models.</p>
<div id="building-a-model-with-lm" class="section level2">
<h2>building a model with lm()</h2>
<p>We’ll start by loading the <code>{tidyverse}</code> and <code>{palmerpenguins}</code> packages, given that we’ll be using contents from both within this post. Then, we’ll return to our scatterplot, but this time I’m going to have R plot the regression line between the two variables we’re interested in. Using ggplot, it’s straightforward to add this line using <code>geom_smooth()</code>. Inside this geom function, I’ve set the <code>method</code> argument to “lm”, which tells R to fit a line to the data identified within <code>aes()</code> using the <code>lm()</code> function.</p>
<pre class="r"><code>library(tidyverse)
library(palmerpenguins)

ggplot(data = penguins, aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;) +
  labs(x = &quot;Flipper Length (mm)&quot;, y = &quot;Bill Length (mm)&quot;)</code></pre>
<p><img src="/post/2021-03-07-a-primer-for-linear-regression-part-2_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>As a small recap from last time, what we’ve just plotted is the line that minimizes the total (summed) squared errors between each point and the line. Now that we’ve visualized our data and the model we’re using to summarize it, let’s try using the <code>lm()</code> function itself.</p>
<pre class="r"><code>fit &lt;- lm(formula = bill_length_mm ~ flipper_length_mm, data = penguins)</code></pre>
<p>These commands aren’t super lengthy, but let’s look carefully at each component. Inside <code>lm()</code>, I’ve specified two arguments: <em>formula</em>, and <em>data</em>. The latter is hopefully self-explanatory; the <code>lm()</code> function needs to know where to find the data that we want to analyze. In this case, I’ve passed it the same data.frame we’ve been using up to now. On the other hand, the <em>formula</em> argument is where we define the relationships we want to model. In R, we do this by writing out an equation, using the language’s “formula” notation. It might be helpful to think of the <code>~</code> in an R formula as sort-of like an equals sign. In the command above, we set our outcome as <code>bill_length_mm</code>, which is to the left of the tilde. On the right-hand side, we have our predictor, <code>flipper_length_mm</code>. R then uses what’s specified in the formula to fit the model, looking in the data for the variable names referenced in the equation. That’s it! We’ve built our first model– now it’s time to take a look at the results.</p>
<p>In R, you can often get information from an object just by printing it. For results produced by <code>lm()</code>, the output is fairly minimal– just the formula and data used, along with the parameter estimates.</p>
<pre class="r"><code># just printing the object
fit</code></pre>
<pre><code>## 
## Call:
## lm(formula = bill_length_mm ~ flipper_length_mm, data = penguins)
## 
## Coefficients:
##       (Intercept)  flipper_length_mm  
##           -7.2649             0.2548</code></pre>
<p>It’s more common to use the <code>summary()</code> function, which produces much more detailed information about the contents/results of our model. We’ll discuss each component in the next few sections.</p>
<pre class="r"><code># more detailed
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = bill_length_mm ~ flipper_length_mm, data = penguins)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.5792 -2.6715 -0.5721  2.0148 19.1518 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -7.26487    3.20016   -2.27   0.0238 *  
## flipper_length_mm  0.25477    0.01589   16.03   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.126 on 340 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.4306, Adjusted R-squared:  0.4289 
## F-statistic: 257.1 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="residuals" class="section level3">
<h3>residuals</h3>
<p>At the top of what comes out of <code>summary()</code> when used on an <code>lm</code> object is a description of the range and distribution of the model’s <em>residuals</em>. Residuals are a really important concept in regression– they’re one of the primary ways we’re able to investigate how well our model fits the data we’re analyzing. In the last post, we actually learned a bit about them, but I didn’t identify them by name.</p>
<p>To more clearly define them, a <em>residual</em> is the difference between each of our penguin’s observed bill-length, and the predicted (fitted) bill-length that’s generated by the model. To revisit a plot I used in the last post, with updated values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, our model’s predicted value for each point is the rising blue line (our regression line). The residuals for each point are the vertical orange segments that measure the distance between each point and the regression line.</p>
<pre class="r"><code>ggplot(penguins, aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_segment(aes(y = (-7.26487 + 0.25477 * flipper_length_mm), yend = bill_length_mm, x = flipper_length_mm, xend = flipper_length_mm), color = &quot;orange&quot;) +
  geom_abline(intercept = -7.26487, slope = 0.25477, color = &quot;blue&quot;) +
  geom_point() +
  labs(x = &quot;Flipper Length (mm)&quot;, y = &quot;Bill Length (mm)&quot;)</code></pre>
<p><img src="/post/2021-03-07-a-primer-for-linear-regression-part-2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>One of the primary ways we can use residuals to check how well our model peforms is by creating <em>diagnostic plots</em>. Here I’m going to use the <code>augment()</code> function from the <code>{broom}</code> package. You pass <code>augment()</code> a model object (often those created by <code>lm</code> or <code>glm</code>), and it generates a new data frame with the predicted/fitted values from the model, as well as residuals.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> You can either calculate these things on your own, or pull fitted values &amp; residuals out of model objects using <code>fitted()</code> and <code>resid()</code>, but using the broom function simplifies things a bit, given that data frames are the standard currency for ggplots.</p>
<pre class="r"><code>library(broom)

# create a data frame with variables used in model + residuals &amp; fitted/predicted values, among other info
aug_fit &lt;- augment(fit)

# don&#39;t miss the periods in front of .fitted and .resid!
ggplot(aug_fit, aes(x = .fitted, y = .resid)) +
  geom_hline(yintercept = 0, lty = &quot;dashed&quot;) +
  geom_point() +
  labs(
    x = &quot;Fitted (Predicted) Values&quot;, y = &quot;Residuals&quot;,
    title = &quot;Fitted vs. Residual Plot&quot;
  )</code></pre>
<p><img src="/post/2021-03-07-a-primer-for-linear-regression-part-2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The above plot is a more traditional way of looking at residuals vs. predicted values. We’ve basically taken our regression line and laid it flat horizontally. In this approach, you can scan across the range of predicted values, checking how each point differs from 0. This style of plot is helpful to examine if one of the classical assumptions for linear regression is met: <em>whether the residuals have a stable variance across the range of predicted values</em>. Just by eye-balling our plot, it feels sketchy to assert that the spread of points is the same across the whole range– in particular, it seems like there’s a difference in points that have predicted values between 40 and 44 vs. elsewhere.</p>
<p>What about the sizes of the differences? If our data was strongly linear, all the points would be really close to 0, but is this about what we would expect if our model was fitting the data well? Are the residuals roughly equally distributed above and below the regression line? This leads us towards another common diagnostic plot, a simple histogram of the residuals. Here we have a frequency distribution for all of our data points, and we can visually check <em>if the residuals have a normal distribution</em> (or approximately normal, being mound shaped &amp; roughly symmetric). If the residuals don’t exhibit this characteristic, it can be another sign that the relationship being modeled isn’t well-represented by a line. In our case, it’s not a perfectly bell-shaped curve, but it’s passable.</p>
<pre class="r"><code>ggplot(aug_fit, aes(x = .resid)) +
  geom_histogram(color = &quot;white&quot;)</code></pre>
<p><img src="/post/2021-03-07-a-primer-for-linear-regression-part-2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="coefficients" class="section level3">
<h3>coefficients</h3>
<p>Now we’ll move on to the next chunk of output, the model coefficients, in this case <span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span>. Here I’m going to use the <code>tidy()</code> function from <code>{broom}</code> to represent this information cleanly as a data frame (tibble). Each variable in the model is placed under the <code>term</code> column, and the coefficient estimates are reported under <code>estimate</code>. In the last post we spent a lot of time talking about how the betas are estimated, and now that we have them, we can talk about the other information that accompanies them.</p>
<pre class="r"><code>tidy(fit)</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term              estimate std.error statistic  p.value
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)         -7.26     3.20       -2.27 2.38e- 2
## 2 flipper_length_mm    0.255    0.0159     16.0  1.74e-43</code></pre>
<p>The 3rd column, <code>std.error</code> is the <em>standard error of the coefficients</em> (sometimes abbreviated “SE”). These represent the level of uncertainty we have for each estimate. <span class="citation">Gelman and Hill (<a href="#ref-gelman2006data">2006</a>)</span> suggests that roughly speaking, “estimates within 2 standard errors of <span class="math inline">\(\hat{\beta}\)</span> are consistent with the data” (p.40).<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> Applying this heuristic to our table, this means that our intercept could be within [-13.7, -0.9] and the coefficient for flipper length could range from [-0.1, 0.6]. Aside from special cases in which two (or more) predictors that are highly correlated with each other are each included in the same model, standard errors should decrease as a function of sample size.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> Assuming your data is representative of the population you’re trying to study, the parameters/coefficients of the model will become more precise as more data is accumulated.</p>
<p>The last two columns, <code>statistic</code> and <code>p.value</code> are tricky to talk about, and I hope to convince you that they’re less interesting than the <span class="math inline">\(\beta\)</span>s and SEs. Although practices are changing, there are sometimes impressions that p-values for model coefficients can be seen as markers of statistical (if not scientific) importance. The story of how this impression gained prominence is complex, and in a future post I might explore a narrow set of reasons for why it’s misguided. For our purposes I hope I can briefly outline what information they <em>do</em> provide. In a single sentence, they’re simply summarizing a ratio of the <span class="math inline">\(\beta\)</span>s and SEs. This ratio is called a <em>t-statistic</em>, and when using linear regression, is computed for each coefficient using the following formula:</p>
<center>
<span class="math inline">\(t_i = \frac{\hat{\beta_i}}{SE(\hat{\beta_i)}}\)</span>
</center>
<p><br></p>
<p>In our case, the t-statistic for flipper length would be 0.255 / 0.0159 = 16.03 – which lines up with what’s reported in our output above. Statistical theory tells us that this value should come from a <em>t-distribution</em>, which can tell us the probability of getting a value as large as, say 16.03, assuming that the expected value was 0. What we can conclude practically here, is that the likelihood of seeing a value of this size under our degrees-of-freedom is really small, and we have some evidence against the assertion that the coefficient is equal to 0. But that’s all we’re learning here; we’re just being told that the slope <em>probably</em> isn’t flat. It’s also worth noting that this is where sample-size becomes relevant for what a significant t-statistic can tell you. As I noted above, SE should decrease as more data is collected. This means that as SE approaches zero, even very small <span class="math inline">\(\beta\)</span>s have a chance to generate a t-statistic that’s associated with a very small p-value.</p>
</div>
<div id="overall-indices-of-fit" class="section level3">
<h3>overall indices of fit</h3>
<p>Okay! We made it to the last section on regression output! 🎉 🎉 🎉 🎉</p>
<p>In this post, we started very zoomed in, looking at differences between predicted vs. actual points, and now we’re finishing with some big-picture aspects of the model overall. We’re going to use another <code>{broom}</code> function, called <code>glance()</code> to pull out this information. Like the <code>tidy()</code> function, <code>glance()</code> also produces a data frame for us to work with.</p>
<pre class="r"><code>glance(fit)</code></pre>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.431         0.429  4.13      257. 1.74e-43     1  -969. 1944. 1955.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<p>The first columns returned are <code>r.squared</code> and <code>adj.r.squared</code>; next to p-values, an <span class="math inline">\(R^2\)</span> (“R-squared”) value is probably one of the most recognizable terms for anyone learning about linear regression. Also referred to as the coefficient of determination, the <span class="math inline">\(R^2\)</span> measures the proportion of the outcome’s variance explained by the model, and ranges from 0 to 1. More specifically, it is defined as <span class="math inline">\(R^2 = 1 - \hat{\sigma}^2 / s^2_y\)</span>, where <span class="math inline">\(\hat{\sigma}^2\)</span> (“sigma squared”) is the unexplained variance of the model, and <span class="math inline">\(s^2_y\)</span> is the variance of the outcome. However, it’s more common in practice to prefer the <em>adjusted R-squared</em>, which accounts for the number of predictors that are included in the model. This is because <span class="math inline">\(R^2\)</span>s generally go up as an analyst adds more &amp; more variables to a model, and thus it’s sensible to adjust for this fact.</p>
<p>This leads us into discussing the next column, <code>sigma</code>, also known as <em>residual standard deviation</em><a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> and often symbolized by <span class="math inline">\(\hat{\sigma}\)</span>. Again referring to <span class="citation">Gelman and Hill (<a href="#ref-gelman2006data">2006</a>)</span> (emphasis mine), “we can think of this standard deviation as a measure of the <em>average distance</em> each observation falls from its prediction from the model” (p.41). This is a useful way of succinctly summarizing the accuracy of the model’s predictions. In our case, our predictions are off by an average of 4.1mm. Perhaps there’s room for improvement!</p>
<p>The next two columns, <code>statistic</code> and <code>p.value</code>, report the results of the model’s F-test, or omnibus test. I don’t want to spend much time on these two, so in brief, the results of this test summarize a comparison between a <em>null model</em> (i.e. a model with just an intercept, and no predictors) versus the fitted model you specified. A large F-statistic and small p-value will occur when at least <em>one</em> of your predictors is better at explaining the outcome than the null model. Phrased differently, this result indicates whether your proposed model is better at predicting the outcome better than just the outcome’s mean. The reason I don’t find this test very useful is that if you look at the estimated coefficients and see any predictor that’s likely different from 0 (i.e. the <span class="math inline">\(\hat{\beta}\)</span> isn’t super close to 0, and its standard error is small), you already have the same information the F-test would provide.</p>
<p>Okay, last few columns from <code>glance()</code>:</p>
<ul>
<li><code>df.residual</code> and <code>df</code>
<ul>
<li>In regression analysis, the <em>degrees of freedom</em> is calculated as <span class="math inline">\(n - k\)</span>, where <span class="math inline">\(n\)</span> is the number of observations, and <span class="math inline">\(k\)</span> is the number of estimated coefficients (including the intercept). In the output from <code>glance()</code>, this information is reported in the <code>df.residual</code> column. The other column, <code>df</code> reports <span class="math inline">\(k\)</span>, but omits the intercept (it can be read as the number of <em>predictors</em> in your model).</li>
</ul></li>
<li><code>logLik</code>, <code>AIC</code>, <code>BIC</code>
<ul>
<li>I’m not going to go in-depth on the output of these columns in this post. Each of these quantities are hard to interpret because their scales aren’t really meaningful in isolation. The <code>deviance</code> column also falls into this category. They become more valuable in the context of <em>model comparison</em>, i.e. when you have multiple sets of predictors, and have specific hypotheses about whether model “A” is better for explaining the outcome compared to model “B”.</li>
</ul></li>
<li><code>nobs</code>
<ul>
<li>This is just the # of observations that were included in your final model. That’s all! Note that R will exclude observations from the results if they have missing data for any of the variables (outcome or predictor) included in the model formula.</li>
</ul></li>
</ul>
</div>
</div>
<div id="okay-mostly-done-with-new-terminology" class="section level2">
<h2>okay, (mostly?) done with new terminology</h2>
<p>Up to now, we’ve covered the following:</p>
<ol style="list-style-type: decimal">
<li>How to plot a regression line using ggplot and <code>geom_smooth()</code>, and how to fit a basic model using <code>lm()</code></li>
<li>Discussed residuals conceptually, and introduced a few common diagnostic plots
<ul>
<li>In relation to this topic, we discussed two assumptions underlying linear regression: a) stable variance in the residuals across the range of fitted values, and b) the distribution of residuals should be normal (or at least, approximately normal).</li>
</ul></li>
<li>Covered how to extract output from a regression model in R, using <code>tidy()</code> and <code>glance()</code>.
<ul>
<li>Here we also talked about the standard error of model coefficients, as well as the overall residual standard deviation, which are important for understanding the uncertainty about the different estimates produced during the analysis.</li>
</ul></li>
</ol>
<p>At this point, I think we’re mostly done with introducing significant concepts and terminology. We’ve worked through most of the components and pieces that comprise a linear regression analysis and the standard kinds of output that R provides. In what I believe will be the <!--[-->final post<!--](/post/primer-for-linear-regression-pt3)-->, we’ll turn to the topic of multiple linear regression (i.e., linear regressions that feature more than 1 predictor), and perhaps touch on some high-level questions (such as how to decide what variables to use).</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2>references</h2>
<div id="refs" class="references">
<div id="ref-gelman2006data">
<p>Gelman, Andrew, and Jennifer Hill. 2006. <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge university press.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>You can also give <code>augment()</code> a new dataset with observations you want predictions for. As long as all the variables used by the model are in your new dataset, you just need to use the equivalent of <code>augment(fit, newdata = my_new_data)</code>.<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>As Gelman and Hill note, this is a bit of a short-cut but they indicate its generally fine to use if the degrees-of-freedom in the model are &gt;30. In the context of linear regression, degrees of freedom can be found by calculating <span class="math inline">\(n - k\)</span>, where <span class="math inline">\(n\)</span> is the number of observations in your data, and <span class="math inline">\(k\)</span> is the number of parameters being estimated.<a href="#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>Honestly, might need a citation here– my recollection is that this can be one of the problems caused by <em>collinearity</em>, and that when variables that correlate strongly (<span class="math inline">\(r \geq 0.5?\)</span>) are included in the same model, both the coefficient estimates can be affected, as well as the standard errors for the affected variables.<a href="#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>Ideally this won’t be distracting, but I want to note that what R labels as “residual standard error” in the output of <code>summary()</code> is actually <strong>residual standard deviation.</strong> I found this initially confusing in terms of trying to understand what I was learning about in textbooks etc. versus what I was being given in my output by R. The help documentation for <code>?sigma</code> explains that this is a quirk of an old misnaming that pre-dates R and existed in its predecessor (the S language). Hopefully this saves you a headache in the long-term!<a href="#fnref4" class="footnote-back">↩</a></p></li>
</ol>
</div>
